### ISSUE TITLE
Entwurf für die Gegenstände erstellen

### ISSUE THREAD

**Issue by MelissaMaas** [Nasanin-Parast/Rollenspiel#12]
**Aufgabenstellung**
Der Entwurf für die Gegenstände ist zu entwerfen. Dazu sind geeignete Diagramme für die Darstellung zu erstellen und im Repository unter docs/KlassendiagrammGegenstaende abzulegen.

**Inhalt**
Die Gegenstände beinhalten folgende Dinge:

- Rüstungsklasse 
- Waffen
- Fallen
- Artefakte für das Spiel 
- Magische Gegenstände 
- Tränke
- Normale

Gamemaster verteilt Artefakte und Fallen.

**Akzeptanzkriterien** 
- [x] Aufbau und Funktionalitäten der Gegenstände sind durch geeignete Diagramme dargestellt
- [x] Das Konzept wurde im Team abgesprochen und genehmigt
- [x] Aus dem Konzept wurden weitere Issues zur Implementierung abgeleitet

**Verknüpfte Issues**
ist Voraussetzung für https://github.com/Nasanin-Parast/Rollenspiel/issues/38

**Offene Fragen** 
--kein--

**Comment by moodyRudi** [comment]
Review: Mir sind ein paar Sachen aufgefallen.
- Klassennamen müssen im Singular stehen; Waffe statt Waffen, Trank statt Traenke etc.
- Brauchen Gegenstände einen Namen? Der Typ des Gegenstands ist ja durch die Unterklasse definiert, mMn braucht ein Gegenstand keinen individuellen Namen. Wenn das aber so umgesetzt werden sollte, ist Gegenstand kein Interface mehr.
- Rüstungsklasse ist für mich nur ein Wert an zusätzlicher Verteidigung, den eine Rüstung liefert. "Ruestung" als Klassenname würde hier vllt besser passen. Auch hier kann man kein Interface nehmen. Was ist die Variable ac, was sUaModifizierer? Hier gerne sprechende Namen wählen. Wie genau funktioniert die Methode verteidigung? Eigentlich verteidigt sich ja ein Spieler und nicht nur die Rüstung? Geht das in die Richtung getRuestungsklasse? Aus der Rüstung könnte man die verschiedenen Rüstungen als Unterklassen ableiten.
- Auch bei Waffen wieder kein Interface. Hier ist wieder der sUaModifizierer, kann man den evtl auslagern? einsetzbarInKampf klingt für mich nach einem boolean, was sagt der int an der Stelle? Das gleiche mit reichweiteUeberEigenesFeldHinaus. anzahlGeschosse passt nicht zu jeder Waffe, oder? Eher in Unterklassen, die die einzelnen Waffen definieren.
- Wie funktioniert die Methode auswirkung in Artefakte? Durch void hat sie keinen Einfluss auf den Aufrufer. Was macht die Methode formAnwendung? Wenn Artefakt ein Interface ist, dann die extends-Pfeile bitte auf implements-Pfeile ändern.
