### ISSUE TITLE
Entwurf für eine Spielfigur erstellen

### ISSUE THREAD

**Issue by Nasanin-Parast** [Nasanin-Parast/Rollenspiel#13]
**Aufgabenstellung**
Zum Einhalten der Programmierrichtlinien und des Erstellens von Schnittstellen soll ein UML-Klassendiagramm für die Spielfigur angelegt und im Repository unter template/spielfigur abgelegt werden.

**Inhalt**:
Jede Spielfigur 
o	hat einen Namen, 
o	eine Charakterklasse (Zauberer, Kämpfer oder Dieb)
o	Lebenspunkte (je nach Charakterklasse und Konstitution) 
o	die Charaktereigenschaften Intelligenz, Stärke, Konstitution, Weisheit und Geschicklichkeit. 
o	Eine Rüstungsklasse (armor class) je nach Charakterklasse, Eigenschaften und Ausrüstung
o	Ein Monster ist eine Spielfigur:
          •     Monster können vom Spielleiter oder zufällig bewegt werden
          •     Sie greifen immer an, wenn Spieler auf sie zugehen.
          •	Es besteht 70% Chance, dass sie eine Gruppe entdeckter Spieler verfolgen. 
          •	Es besteht 10% Chance, dass sie weglaufen

**Akzeptanzkriterien:**
- [x] Es wurde ein UML-Klassendiagramm für eine Spielfigur erstellt. Alle wichtigen Anforderungen des Lastenheft wurden erfüllt.

**Zu Berücksichtigende Punkte sind:**
Lebenspunkte :
   •  Krieger: 10 LP, Dieb 8 LP Magier 6 LP
   •  Gemäß dem Konstitutionswert werden weitere Lebenspunkte zum Basiswert hinzugerechnet 
       (Modifizierung). 
       Bsp. Ein Magier hat 8 LP als Basis und einen Konstitunswert von 15. 
       8 + (15 – 10) / 2 = 8 + 2,5 = 10,5 --> 10 LP
       Als Ergebnis hat er 10 Lebenspunkte.

ist Voraussetzung für #3 
Offene Fragen

**Comment by moodyRudi** [comment]
Review: Mir sind ein paar Kleinigkeiten aufgefallen, die noch mit berücksichtigt werden sollten:
- Die Charaktereigenschaft Konstitution fehlt in der Spielfigur.
- Ich würde hier noch eine Klasse zwischen der Spielfigur und Dieb/Kämpfer/Magier machen, damit die Unterscheidung zwischen Monstern und spielbaren Figuren deutlich wird. Außerdem braucht man diese Unterscheidung, wenn mehrere Spielfiguren auf einem Feld stehen. Einige Eigenschaften, wie eine eigene Sichtweite, trifft auch nur auf spielbare Charaktere zu. Die kann dann später in genau dieser Klasse umgesetzt werden.
- Eine Spielfigur muss mehrere Artefakte bzw. Gegenstände besitzen können. (Artefakte sind nur spezielle Gegenstände)
- Der Modifizierer wird für mehrere Sachen benötigt. Evtl würde es Sinn machen, eine eigene Methode zur Berechnung zu implementieren, oder diese sogar auszulagern, falls andere Klassen die gleiche Berechnung benötigen.
- Es fehlt mir ein Konstruktor, über den man die Charaktereigenschaften setzen kann.

**Comment by Nasanin-Parast** [comment]
Danke für das Review. Die Unterklassen sind nicht vollständig und werden erst in anderen Tickets bearbeitet. Deine Anmerkungen habe ich berücksichtigt.
