### ISSUE TITLE
Entwurf für Spielablauf erstellen

### ISSUE THREAD

**Issue by moodyRudi** [Nasanin-Parast/Rollenspiel#14]
**Aufgabenstellung**
Der Entwurf für den kompletten Spielablauf ist zu erstellen. Dazu sind geeignete Diagramme für die Darstellung zu erstellen und im Repository unter src/template/spielablauf abzulegen.

**Inhalt**
Der Game Master kann einen neuen Spielplan erstellen und speichern. Er verteilt dabei Monster, Artefakte und Fallen.
Spieler können einen neuen Charakter erstellen. Dabei könne sie einen Namen vergeben und Werte den Charaktereigenschaften zuordnen.
Vor dem Spiel werden die Charaktere ausgesucht. Bei Spielbeginn wird ein einleitender Text angezeigt. Die Charaktere werden automatisch am Eingang des Dungeon platziert. Danach beginnen die Spielrunden. Am Ende einer Spielrunde kann eine Kampfrunde stattfinden.
Das Spiel endet, wenn alle Spieler tot sind oder das Ziel erreicht wurde.

**Akzeptanzkriterien**
- [x] Der Spielablauf ist durch geeignete Diagramme dargestellt
- [x] Alle offenen Fragen wurden vom Kunden geklärt
- [ ] Das Konzept wurde im Team abgesprochen und genehmigt
- [x] Aus dem Konzept wurden weitere Issues zur Implementierung abgeleitet

**Verknüpfte Issues**
- ist Voraussetzung für #20 
- ist Voraussetzung für #21 
- ist Voraussetzung für #22 

**Offene Fragen**
--keine--

**Comment by moodyRudi** [comment]
Ich habe insgesamt 4 Diagramme für den Spielablauf erstellt. 1 Anwendungsfalldiagramm zur Übersicht, sowie 3 Aktivitätsdiagramme für die Anwendungsfälle Spielplanerstellung, Charaktererstellung und Spielablauf. Auf die Spiel- und Kampfrunden bin ich nicht genauer eingegangen, diese werden in den dafür vorgesehenen Issues bearbeitet. Die Issues zur Implementierung der Anwendungsfälle sind oben verlinkt.

**Comment by Nasanin-Parast** [comment]
Review: Das Konzept passt nur die Reihenfolge bei der Charaktererstellung soll angepasst werden. Schritte 4 und 5 soll ausgetauscht werden.
