### ISSUE TITLE
Spieler implementieren

### ISSUE THREAD

**Issue by Nasanin-Parast** [Nasanin-Parast/Rollenspiel#18]
**Aufgabenstellung**
Der in Issue #15  erstellte Entwurf ist zu implementieren und zu testen.

**Inhalt**
wird durch Issue #15  noch genauer definiert -

**Akzeptanzkriterien**
- [x]  Der Spieler ist implementiert
- [x] Der Spieler ist durch Unit-Tests abgedeckt
- [x] Die Diagramme zum Spieler sind angepasst
- [x] Die Änderungen sind erfolgreich nach master gebracht
- [x] Dokumentation ist dazu geschrieben

**Verknüpfte Issues**
#15 

**Offene Fragen**

**Comment by moodyRudi** [comment]
Der Spieler wurde auch im Rahmen der Spielfigur angepasst
