### ISSUE TITLE
Charaktererstellung implementieren

### ISSUE THREAD

**Issue by moodyRudi** [Nasanin-Parast/Rollenspiel#21]
**Aufgabenstellung**
Unter src/template/spielablauf ist ein Aktivitätsdiagramm zum Erstellen eines Charakters abgelegt. Die dort enthaltenen Schritte sind zu implementieren.

**Inhalt**
Zu Beginn wählt der Spieler eine Charakterklasse. Dann erstellt das System 5 zufällige Werte zwischen 3 und 18. Solange die Summe aller Werte kleiner als 60 ist, wird der geringste Wert neu ermittelt. Der Spieler kann dann die Werte den 5 Charaktereigenschaften zuordnen.
Zum Schluss wählt er noch eine Rasse und legt einen Namen fest. Der fertige Charakter wird gespeichert.

**Akzeptanzkriterien**
- [x] Sämtliche Funktionalitäten sind implementiert und getestet
- [x] Alle offenen Fragen wurden vom Kunden geklärt
- [x] Die bestehenden Entwürfe wurden, falls nötig, ergänzt bzw. erweitert

**Verknüpfte Issues**
- setzt voraus #14 und #15 

**Offene Fragen**
--keine--

**Comment by Nasanin-Parast** [comment]
Die Factory-Klasse, CharakterBuilder-Klasse mit ihren Unterklassen wurde implementiert und mit 100% Coverage getestet. Aktuell können Charakteren erstellt werden und noch eine Rasse mit Namen festgelegt werden.
