### ISSUE TITLE
UI für Spieler entwerfen

### ISSUE THREAD

**Issue by Boevenius** [Nasanin-Parast/Rollenspiel#26]
### Aufgabenstellung
Der Entwurf für die UI eines Spielers ist zu erstellen. Dazu sind geeignete Diagramme für die Darstellung zu erstellen und im Repository under template/UI abzulegen.

### Inhalt
Jeder Spieler hat seine eigene Ansicht und kann auch nur mit dieser Interagieren. (Reduzierung auf es ist immer nur eine Spieleransicht gleichzeitig freigeschaltet.)
Der Spieler soll auf sein eigenes Inventar zugreifen können, seine eigene Spielfigur sehen und seine eigenen Eigenschaften sehen können.
Der Spieler ist in der Lage seine eigene Spielfigur zu bewegen und seine Ausrüstung zu ändern.
Befindet sich der Spieler im Kampf, so ist er in der Lage alle Aktionen einer Kampfrunde die auf seine eigene Figur zugeschnitten sind zu benutzen.

### Akzeptanzkriterien

- [x] Diagramm für alle Funktionalitäten wurden erstellt
- [x] Alle offenen Fragen wurden vom Kunden geklärt
- [x] Das Konzept wurde im Team abgesprochen und genehmigt
- [x] Aus dem Konzept wurden weitere Issues zur Implementierung abgeleitet

### Offene Fragen

**Comment by moodyRudi** [comment]
Bitte noch ein neues Ticket für die Implementierung erstellen, dann ist das hier abgeschlossen.
