### ISSUE TITLE
UI für Inventar entwerfen

### ISSUE THREAD

**Issue by Boevenius** [Nasanin-Parast/Rollenspiel#27]
### Aufgabenstellung
Der Entwurf für ein UI für das Inventar wurde erstellt. Dazu sind geeignete Diagramme für die Darstellung zu erstellen und im Repository unter templates/UI abzulegen.

### Inhalt
Im Inventar sollen alle Gegenstände eines Spieler zu sehen sein, sowie die Eigenschaften des Gegenstandes. Zudem sollen auch alle Aktionen eines ausgewählten Gegenstandes zu sehen sein. (z.B. Gegenstand benutzen, Gegenstand anlegen, etc.)
Jeder Spieler hat sein eigenes Inventar, der Gamemaster kann alle Inventare einsehen.

### Akzeptanzkriterien

- [x] Diagramm für alle Funktionalitäten wurden erstellt
- [x] Alle offenen Fragen wurden vom Kunden geklärt
- [x] Das Konzept wurde im Team abgesprochen und genehmigt
- [ ] Aus dem Konzept wurden weitere Issues zur Implementierung abgeleitet

### Offene Fragen

**Comment by moodyRudi** [comment]
Bitte noch ein neues Ticket für die Implementierung erstellen, dann ist das hier abgeschlossen.
