### ISSUE TITLE
UI für Kampf entwerfen

### ISSUE THREAD

**Issue by Boevenius** [Nasanin-Parast/Rollenspiel#28]
### Aufgabenstellung
Der Entwurf für ein UI für den Kampf wurde erstellt. Dazu sind geeignete Diagramme für die Darstellung zu erstellen und im Repository unter templates/UI abzulegen.

### Inhalt
Sobald ein Kampf beginnt, müssen alle Spieler in der Lage sein zu sehen welche Spieler und Monster am Kampf beteiligt sind. Zudem sollten Statusinformationen zum Kampf und den Spielern, so wie aktuelle Informationen zu den Angriffen und Zaubern verfügbar sein.
Spieler müssen Zugriff auf ihr Inventar haben und Gegenstände einsetzen können. Monster müssen vom Gamemaster 'gemeinsam' gesteuert werden können.

### Akzeptanzkriterien

- [x] Diagramm für alle Funktionalitäten wurden erstellt
- [x] Alle offenen Fragen wurden vom Kunden geklärt
- [x] Das Konzept wurde im Team abgesprochen und genehmigt
- [x] Aus dem Konzept wurden weitere Issues zur Implementierung abgeleitet

### Offene Fragen

**Comment by moodyRudi** [comment]
Bitte noch ein neues Ticket für die Implementierung erstellen, dann ist das hier abgeschlossen.
